server:
  port: 8082

spring:
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/mediappbd7
    username: postgres
    password: 123

